### ISSUE TITLE
hi, i build copyq appimage with ArchImage , i find some proble

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/ArchImage#11]
first, copyq appimage with Archimage build is have more size  300MB

so, how do you decrease the appimage size with use Archimage-cli

**Comment by ivan-hc** [comment]
My deletions are from line 115 to 1256.

- if something does not works because I removed something, remove that group of lines between 115 ans 1256 (the AppImage will be bigger);
- if the ArchImage works and you want to made it smaller, test it by running the AppRun and guess what files the final AppImage should not include. My workflow is:

1. move a file/a group of files/a directory/more directories in the thrash;
2. run the AppRun;
3. if the app works I can sign the files I removed to add them in the list of files to delete... if the app does  not work I must restore the removed files from th thrash;
4. repeat from the point 1 to the poit 3 with another file, folder or a group of files.

I don't know when I do well, nor if I am wrong. I just guess if the files are needed or not.
