### ISSUE TITLE
Building errors Quiltix from AUR

### ISSUE THREAD

**Issue by dCo3lh0** [ivan-hc/ArchImage#13]
Hey man, i've tried using archimage to build a tool that is very hard to build for linux and someone did in AUR, but i am in debian 11 so i thought, why not trying to make an appimage using archimage and junest, so i've tried but it gave me an error at the end, about missing python or something. Can you help me on this? I just wanna try the tool. i've pointed the dependencies as well but it didn't find python at all.

Original Repository:
https://github.com/PrismPipeline/QuiltiX

AUR:
https://aur.archlinux.org/packages/quiltix

**Comment by ivan-hc** [comment]
I must read the log, is python a dependence? You need to add this at top of the script.

**Comment by dCo3lh0** [comment]
there is various log files inside the folder, what log file do you want? i dont know what to post lmao. What terminal command line i use to generate a build log.

**Comment by ivan-hc** [comment]
You have not said if the AppImage has been created. Be more specific. If you say
> it gave me an error at the end, about missing python or something

this does not helps.

I can imagine a series of things:
- a missing dependency, so the appimage is ready but doesn't work
- you can't create the appimage because you miss a compiler for the AUR package
- etcetera... etcetera... etcetera

All I say is that everyone that wants to create an Appimage using my ArchImage tool should try to install it on JuNest first, and then take notes of every missing package that it needs to made the app work.

My question is "Are you able to install the app from AUR on Arch Linux?"
- If your answer is YES, so I understand that the AppImage is created but doesn't work, so I can help understanding what dependence is missing (because is that the problem);
- If your answer is NOPE, so you should install it on Arch Linux first (using JuNest obviously), so you will be sure that the AppImage can be created.

I'm telling you this because you wrote me two messages and I still don't understand what your problem is (and I don't like having to guess).

**Comment by ivan-hc** [comment]
OK, I've tried to compile this by myself. 

I think that your problem is while compiling, so all processes are stuck at this point:

![Istantanea_2023-11-21_03-24-33](https://github.com/ivan-hc/ArchImage/assets/88724353/1de6ad65-953f-4df5-84b1-09405cbce9e4)

The first time I had only `python` as dependence.

The second time I compiled everything I have used this dependence: `base-devel` (as described [here](https://github.com/fsquillace/junest#cannot-use-aur-repository)).

This should be already all we need. Change the line DEPENDENCES in the script, the only dependence you need is `base-devel`

```
DEPENDENCES="base-devel"
```

because all the dependences listed on the AUR are AUR packages themself (I had also ChaoticAUR support enabled, to speedup the workflow).

In both cases I had the same issue shown in the screenshot.

I don't know why this happens, it should be better to ask to the maintainer of the PKGBUILD or to search among the forums.

```
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
/usr/bin/python: No module named build
==> ERROR: A failure occurred in build().
    Aborting...
```

by doing a quick search on Google, it seems that "build" must be compiled from source using "pip install".

I don't know if the author of the PKGBUILD have obmitted this step or something. It is better if you try to solve this issue before you start compilng again this ArchImage.

Sources:
- https://www.google.com/search?q=quiltix+error+python%3A+No+module+named+build&client=firefox-b-d&sca_esv=584157642&ei=rhZcZbXDEq-V9u8P1IWRiAI&ved=0ahUKEwi10tTIhtSCAxWviv0HHdRCBCEQ4dUDCBA&uact=5&oq=quiltix+error+python%3A+No+module+named+build&gs_lp=Egxnd3Mtd2l6LXNlcnAiK3F1aWx0aXggZXJyb3IgcHl0aG9uOiBObyBtb2R1bGUgbmFtZWQgYnVpbGQyBRAhGKABMgUQIRigAUi-jQFQmwNYioUBcAJ4AJABAJgBfqABnAaqAQM0LjS4AQPIAQD4AQH4AQLCAgoQABiABBgTGLADwgIHEAAYgAQYE-IDBBgBIEGIBgGQBgI&sclient=gws-wiz-serp
- https://stackoverflow.com/questions/76135728/no-module-named-build-main-build-is-a-package-and-cannot-be-directly-ex

**Comment by ivan-hc** [comment]
New commit with additional checks https://github.com/ivan-hc/ArchImage/commit/a97a96763b6727a223908c4ccf3614bc55649edf

- added authentication key for AUR (optional);
- if an error occurs, prevent the AppImage from being created (.desktop file availability check).

In case of problens, replace the part "# INSTALL THE PROGRAM USING YAY" with this one:
```
# INSTALL THE PROGRAM USING YAY
./.local/share/junest/bin/junest -- yay -Syy
./.local/share/junest/bin/junest -- gpg --keyserver keyserver.ubuntu.com --recv-key C01E1CAD5EA2C4F0B8E3571504C367C218ADD4FF
echo y | ./.local/share/junest/bin/junest -- yay --answerclean All --answerdiff All --noconfirm -S gnu-free-fonts $(echo "$BASICSTUFF $COMPILERS $DEPENDENCES $APP")
```
I use it to built "gimp-git" https://github.com/ivan-hc/GIMP-appimage/blob/main/gimp-git-junest.sh
