### ISSUE TITLE
i use ArchImage to success build copyq , but copyq not show china font

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/ArchImage#5]
![image](https://github.com/ivan-hc/ArchImage/assets/87791643/0681daef-40ce-45b6-91ed-0c92637e6a33)
![image](https://github.com/ivan-hc/ArchImage/assets/87791643/341a973b-56b0-4548-92a0-5046fda2082d)

how can when i use ArchImage to build Appimage file , merge china font 
or i have idea, copy local system font.

this is my local system font, how can copy it Appimage file when i build it
```
❯ ls /usr/share/fonts/
cmap/  cMap/  FontAwesome/  JetBrainsMono/  MonoLisa-Trial-2.008-ttf/  opentype/  truetype/  type1/  X11/  霞鹜文楷/
```

**Comment by ivan-hc** [comment]
We have already faced this issue https://github.com/ivan-hc/OBS-Studio-appimage/issues/3#issuecomment-1635923915

You should add `--bind=/usr/share/fonts` in the AppRun to see the fonts from the host

Maybe you should also add `--bind=/usr/share/fontconfig` if something doesn't works. Just in case.

Anyway, this is not a default option because sometime the app does not recognize it.

Optionally, add fonts for your language as a dependence (search the package/packages from Arch Linux repositories), this will take more space, but the app should work the way you desire.
