### ISSUE TITLE
how can build like Vmware workstation , secure CRT software when using archimage tool , that is means cool

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/ArchImage#9]
ArchImage can build Thired package that's awesome

**Comment by ivan-hc** [comment]
I didn't understand your question, it's a bit confusing... but if you try to build VMware or VirtualBox, leave it. They require KVM and direct use of kernel modules. JuNest, like docker and podman, is a container manager. You can't do everything from a container... so you can't convert all solutions to AppImages. I've tried to build gnome-boxes [here](https://github.com/ivan-hc/Boxes-appimage) and I still have issues to made it work correctly.

PS: since it is so easy for you to open random "issues" of all kinds on my repositories as if they were chat messages, I warn you that I do not provide any support on my version of GNOME Boxes, I need help there myself. So don't open other useless and unnecessary "issues". I have Reddit if you want to chat. Thank you.
